### ISSUE TITLE
Instructions for CircleCI

### ISSUE THREAD

**Issue by nbibler** [thoughtbot/appraisal#100]
The README has instructions for using Appraisal with TravisCI. However, Suspenders was just [updated to use CircleCI](https://github.com/thoughtbot/suspenders/blob/master/NEWS.md) and yet Appraisal contains no information about CircleCI integration.

After searching around a bit, it [does not appear to be a straightforward configuration](http://www.jetthoughts.com/blog/tricks/2014/11/24/run-tests-against-multiple-ruby-versions-on-circleci.html) setting in the `circle.yml`.

Are there any official Appraisal configuration settings for CircleCI? And if so, can they be added to the README?

**Comment by jferris** [comment]
You could install and run Appraisal on CircleCI, but I prefer to use Travis for projects that require a build matrix. Even if you get Appraisal working on CircleCI, you'll still have more hoops to jump through to get multiple Ruby versions going.

@sikachu any thoughts?

**Comment by nbibler** [comment]
That's fair. Travis makes the matrix stuff (multiple language versions, environment settings, etc.) very simple.

It just seemed as though Thoughtbot was seemingly moving toward CircleCI with the Suspenders change, but yet wasn't doing it across all of the projects. Looking into it, I've kind of realized why - at least for Appraisal. As you mentioned, it seems to be incredibly complicated / brittle to do right now.

**Comment by jferris** [comment]
> It just seemed as though Thoughtbot was seemingly moving toward CircleCI with the Suspenders change

Yeah, we definitely are. If Circle had better support for multiple versions, I would probably move my open source projects over.

**Comment by sikachu** [comment]
I don't think Suspender's change affects Appraisals (or CI service change) in any way, as usually you will only testing your Rails application against only one set of gems and one version of Ruby, whereas for gem development (which we still run the test on Travis) you have to run it against multiple versions, and that's where Appraisals comes in to play.

For open source projects, I still don't see CircleCI as a viable choice as you can only have 1 concurrent build where on Travis you can spawn ~5 concurrent builds for free. I feel like _unless you have a good reason to do so_ Travis is still a better option.

With that said, I don't mind if you would like to submit a PR to add section about how to config the test on CircleCI, with the caveat that they probably have to pay for additional container (as otherwise it would be just as running `appraisal rake` like you do it locally).

I'm going to close this, but please feel free to discuss further or submit a PR to add that.
