### ISSUE TITLE
Support git_source

### ISSUE THREAD

**Issue by fx** [thoughtbot/appraisal#103]
See https://github.com/bundler/bundler/blob/20f04aa8923c0d0f02e7a74d5e9609d772351668/man/gemfile.5.ronn#L336

````/usr/local/rvm/gems/ruby-2.2.3/gems/appraisal-2.1.0/lib/appraisal/gemfile.rb:21:in `run': undefined method `git_source' for #<Appraisal::Gemfile:0x000000031eb740> (NoMethodError)
        from /usr/local/rvm/gems/ruby-2.2.3/gems/appraisal-2.1.0/lib/appraisal/gemfile.rb:20:in `instance_eval'
        ...````

**Comment by sikachu** [comment]
I was trying to look into this. However, it doesn't seems as straightforward as I hoped because of how Ruby block works.

Since Appraisal needs to parse the file, it means that we are reading that block and stores it. However, there's no good way to restore that block black into Ruby source code.

One way we could do it is to perform interpolation inside Appraisal, so if you have:

```ruby
git_source(:github){ |repo_name| "https://github.com/#{repo_name}" }

gem "rails", github: "rails/rails"
```

Your generated gemfile will contain:

```ruby
gem "rails", git: "https://github.com/rails:
```

Do you think that's a good compromise?

**Comment by fx** [comment]
I can't really comment on this, I don't actively use appraisal anywhere. So I'll defer to your judgement @sikachu :)

**Comment by sikachu** [comment]
Alright. Thinking about it, I think evaluate `git_source` block at `appraisal generate` time is acceptable since:

1. This will make us support `git_source` block.
2. We're not recommending people editing generated gemfiles anyway.

I'll add support for this in the next minor version.
