### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by nijikon** [thoughtbot/appraisal#212]
Can you please craft a new release of the gem? I hit a similar issue that was described here https://github.com/thoughtbot/appraisal/issues/211. Switching to the main branch fixed the issue.

**Comment by nijikon** [comment]
cc @nickcharlton

**Comment by xjunior** [comment]
Furthermore, I'm trying to use `customize_gemfile` as shown on the main page of this project, and it's only present on the unreleased version.

**Comment by nickcharlton** [comment]
Thanks for poking me. 

I'll take a look today (…worse it'll be tomorrow if I run out of time) but I think we can probably do a minor release now. I'd been holding off because we've not made much/enough progress on handling newer Bundler versions, but I think this must be causing us all enough annoyance.

**Comment by nijikon** [comment]
@nickcharlton yes, the minor would be ideal. Thank you very much for your work on this project 💜
